"""One schema definition rendered for both durable backends.

The journal, projection, and outbox exist once as SQL. A dialect supplies only
the handful of spellings SQLite and PostgreSQL genuinely disagree about, so
neither backend can drift into its own behavior.
"""

from __future__ import annotations

from dataclasses import dataclass

_BYTE_ORDER_MARKER = "/*bytes*/"

PENDING_STATE = "pending"
SETTLED_STATE = "settled"


@dataclass(frozen=True, slots=True)
class _Dialect:
    """The spellings that differ between the two supported backends."""

    placeholder: str
    # A surrogate receipt-order key that is never reused after deletion,
    # because replay ordering and refresh tokens are both derived from it.
    receipt_order_column: str
    # Text that participates in ordering or range comparison. PostgreSQL's
    # default locale can order text differently from SQLite and from Python,
    # so any column a cursor compares is pinned to byte order explicitly.
    ordered_text: str
    # The same pin applied to an expression rather than a column declaration,
    # for columns that were already shipped unpinned and cannot be retyped
    # without rewriting the table.
    order_by_bytes: str


SQLITE_DIALECT = _Dialect(
    placeholder="?",
    receipt_order_column="INTEGER PRIMARY KEY AUTOINCREMENT",
    ordered_text="TEXT",
    # SQLite compares TEXT with BINARY unless told otherwise, which is already
    # byte order.
    order_by_bytes="",
)

POSTGRES_DIALECT = _Dialect(
    placeholder="%s",
    receipt_order_column="BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    ordered_text='TEXT COLLATE "C"',
    order_by_bytes=' COLLATE "C"',
)


_TABLES = (
    """
    CREATE TABLE IF NOT EXISTS journal_events (
        receipt_order {receipt_order_column},
        principal_id TEXT NOT NULL,
        event_id {ordered_text} NOT NULL,
        room_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        kind TEXT NOT NULL,
        sender TEXT NOT NULL,
        origin_server_ts BIGINT NOT NULL,
        source_json TEXT NOT NULL,
        semantic_consumer TEXT,
        -- The membership this event was admitted under, which is what refuses
        -- an answer written for a conversation the bot has since left. Read by
        -- `admitted_membership_epoch` and by nothing else.
        membership_epoch BIGINT NOT NULL,
        state TEXT NOT NULL CHECK (state IN ('pending', 'settled')),
        UNIQUE (principal_id, event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS visible_messages (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        logical_event_id {ordered_text} NOT NULL,
        thread_id TEXT NOT NULL,
        sender TEXT NOT NULL,
        created_ts BIGINT NOT NULL,
        revision_event_id {ordered_text} NOT NULL,
        revision_ts BIGINT NOT NULL,
        content_json TEXT,
        refresh_token BIGINT,
        membership_epoch BIGINT NOT NULL,
        PRIMARY KEY (principal_id, room_id, logical_event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS unresolved_edits (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        target_event_id TEXT NOT NULL,
        sender TEXT NOT NULL,
        edit_event_id {ordered_text} NOT NULL,
        edit_ts BIGINT NOT NULL,
        content_json TEXT NOT NULL,
        PRIMARY KEY (principal_id, room_id, target_event_id, sender)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS redaction_tombstones (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        redacted_event_id TEXT NOT NULL,
        PRIMARY KEY (principal_id, room_id, redacted_event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS room_membership (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        membership_epoch BIGINT NOT NULL,
        -- A departure has been fenced and the bot has not been seen back in
        -- the room since. The bot cannot leave a room it is not in, so a
        -- second local departure while this holds is the same one arriving
        -- twice rather than a new one.
        departure_fenced INTEGER NOT NULL DEFAULT 0,
        -- Departures already fenced locally whose sync report has not arrived.
        -- A count rather than a flag: leave/rejoin/leave owes two reports, and
        -- one bit would let the second echo fence a membership it did not end.
        owed_departure_reports BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY (principal_id, room_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS conversation_hydration (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        membership_epoch BIGINT NOT NULL,
        -- Whether the walk that filled this conversation ran out of
        -- conversation rather than out of allowance. Being hydrated and being
        -- complete are different facts: a walk that stopped at the prompt
        -- window is hydrated, and a reader whose correctness is completeness
        -- has to be able to tell that from a whole conversation. It is the
        -- best answer any walk gave under this membership rather than the
        -- newest one: walks of different widths run concurrently over this
        -- row, and the narrower finishing last must not un-say the wider.
        complete INTEGER NOT NULL DEFAULT 0,
        -- The rank of the widest-ranked `HydrationPolicy` any walk here has run
        -- under this membership, whether or not it got anywhere. Completeness
        -- alone cannot distinguish a conversation nobody walked deeply from one
        -- where the deepest available walk has already been spent and failed,
        -- and a caller that cannot tell those apart repeats its whole walk on
        -- every read of a conversation that will never satisfy it. A policy
        -- rank rather than one of its ceilings, because a caller is defined by
        -- all three of them together and two policies can differ on any one.
        -- Also the best answer rather than the newest, for the reason above.
        attempted_policy_rank BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY (principal_id, room_id, thread_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS room_history_recovery (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        state TEXT NOT NULL CHECK (state IN ('repairable', 'truncated', 'repaired')),
        revision BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY (principal_id, room_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS response_outbox (
        principal_id TEXT NOT NULL,
        turn_id TEXT NOT NULL,
        stage TEXT NOT NULL CHECK (stage IN ('initial', 'final')),
        room_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        transaction_id TEXT NOT NULL,
        payload_json TEXT NOT NULL,
        edits_event_id TEXT,
        attempted INTEGER NOT NULL DEFAULT 0,
        -- The device whose transaction ID the homeserver may already hold. A
        -- transaction ID deduplicates within one device, so a row attempted by
        -- a device this process is no longer logged in as carries an ID that
        -- would be accepted as new -- and post the answer twice.
        sending_device_id TEXT,
        acknowledged_event_id TEXT,
        created_at_ns BIGINT NOT NULL,
        PRIMARY KEY (principal_id, turn_id, stage)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS approval_cards (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        -- The card's identity, chosen by this bot before the card is sent and
        -- reused as the Matrix transaction ID. The homeserver assigns the event
        -- ID, so keying on that would mean no row could exist until after the
        -- send -- which is the one ordering that can leave a clickable card
        -- nothing accounts for.
        transaction_id TEXT NOT NULL,
        -- NULL until the send returns an event ID. Such a row is a card that
        -- may or may not be in the room; presenting the frozen transaction
        -- again is what settles which, because the homeserver collapses a
        -- repeat onto the event it already accepted.
        card_event_id TEXT,
        -- Whether this card was ever offered to the homeserver. Claiming is not
        -- offering: the row is committed first, so a process that dies in
        -- between leaves a claim for a card that provably never left it. Only
        -- an attempted row can have put something clickable in the room, and
        -- only an attempted row therefore has to be reconciled against it.
        --
        -- No default. Every insert names it, and a row that failed to would be
        -- a claim nothing could account for; refusing it is better than guessing.
        attempted INTEGER NOT NULL,
        -- The device whose transaction-ID namespace was used, written with
        -- `attempted` and only by the path that is about to send. Only that
        -- device's repeat is deduplicated by the homeserver; from any other it
        -- is a second card, so a row whose device cannot be matched is
        -- reconciled against the room instead of presented again.
        sending_device_id TEXT,
        card_json TEXT NOT NULL,
        -- The decision this bot committed to before it tried to show it. A
        -- card is answered the moment this is set, whether or not the edit
        -- carrying it reached the room.
        resolution_json TEXT,
        membership_epoch BIGINT NOT NULL,
        created_at_ns BIGINT NOT NULL,
        PRIMARY KEY (principal_id, transaction_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS turn_records (
        -- Scoped to the agent, not to a journal principal. Every other table
        -- here is per (agent, Matrix identity), because what it holds is only
        -- meaningful next to the sync that produced it. A turn record is not:
        -- it is the proof that a message was already answered, and a bot that
        -- re-logs in under a new Matrix ID must not answer everything twice.
        -- Sharing the database is what makes this transactional with a
        -- settlement; sharing the scope key is not required and would be wrong.
        agent_name TEXT NOT NULL,
        -- A coalesced turn answers several sources at once and is reachable by
        -- any of them, so one record is stored once per event that indexes it.
        index_event_id TEXT NOT NULL,
        anchor_event_id TEXT NOT NULL,
        record_json TEXT NOT NULL,
        PRIMARY KEY (agent_name, index_event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS journal_identity (
        -- One row, ever. A Matrix sync token is only meaningful next to the
        -- store that consumed the events it already covers: resuming from a
        -- token saved before this database was created would skip every event
        -- between, and nothing downstream would notice the gap. The generation
        -- is written once when the store is first opened and never rewritten,
        -- so a checkpoint that names a different one is from a database that
        -- no longer exists.
        singleton BOOLEAN NOT NULL PRIMARY KEY,
        generation TEXT NOT NULL
    )
    """,
)


_INDEXES = (
    """
    CREATE INDEX IF NOT EXISTS journal_events_pending
    ON journal_events (principal_id, receipt_order)
    WHERE state = 'pending'
    """,
    """
    -- The replay guard asks whether one conversation holds newer unfinished
    -- work. `journal_events_pending` orders the principal's whole pending set
    -- by receipt, so answering from it means filtering every pending row in
    -- every room; this one goes straight to the thread and the timestamp.
    CREATE INDEX IF NOT EXISTS journal_events_pending_thread
    ON journal_events (principal_id, room_id, thread_id, origin_server_ts)
    WHERE state = 'pending'
    """,
    """
    CREATE INDEX IF NOT EXISTS visible_messages_page
    ON visible_messages (principal_id, room_id, thread_id, created_ts, logical_event_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS visible_messages_revision
    ON visible_messages (principal_id, room_id, revision_event_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS visible_messages_refresh
    ON visible_messages (principal_id, room_id, thread_id)
    WHERE refresh_token IS NOT NULL
    """,
    """
    -- Covers the recovery scan's whole ORDER BY, not just its prefix. Stopping
    -- at `created_at_ns` left SQLite building a temporary b-tree for the last
    -- two terms on every pass, and PostgreSQL cannot satisfy an ORDER BY from
    -- an index that matches only its prefix either. The trailing columns carry
    -- the same byte-order pin as the cursor comparison, because an index in the
    -- server's own collation would not be usable for this ordering at all.
    CREATE INDEX IF NOT EXISTS response_outbox_unacknowledged_scan
    ON response_outbox (principal_id, created_at_ns, turn_id/*bytes*/, stage/*bytes*/)
    WHERE acknowledged_event_id IS NULL
    """,
    """
    -- Tied on `transaction_id` rather than the event ID, which is nullable now:
    -- the two backends disagree about where NULLs sort, so an order broken on
    -- that column would page one room's cards differently on each.
    CREATE INDEX IF NOT EXISTS approval_cards_room_transaction_scan
    ON approval_cards (principal_id, room_id, created_at_ns, transaction_id/*bytes*/)
    """,
    """
    -- One card per accepted event. The partial predicate is what lets many rows
    -- sit unacknowledged at once, since only a recorded event ID is claimed.
    CREATE UNIQUE INDEX IF NOT EXISTS approval_cards_event
    ON approval_cards (principal_id, card_event_id)
    WHERE card_event_id IS NOT NULL
    """,
)


def _expand_byte_order(sql: str, dialect: _Dialect) -> str:
    """Spell the byte-order pin for one backend."""
    return sql.replace(_BYTE_ORDER_MARKER, dialect.order_by_bytes)


def schema_statements(dialect: _Dialect) -> tuple[str, ...]:
    """Return every DDL statement needed to create the schema.

    Creation only. There is no upgrade path and deliberately so: this schema
    has never shipped, so the only databases carrying an older shape are
    prerelease ones on this branch, and those are required to be deleted rather
    than migrated.

    The byte-order marker is substituted here as well as in queries. An index
    whose trailing columns sort in the server's own collation cannot satisfy an
    ORDER BY that pins them to byte order -- PostgreSQL simply declines to use
    it and sorts instead. Leaving the marker unexpanded is silent on SQLite,
    whose default text collation is already byte order, so the mismatch shows up
    only on the backend that is not measured by a local query-plan test.
    """
    return tuple(
        _expand_byte_order(statement, dialect).format(
            receipt_order_column=dialect.receipt_order_column,
            ordered_text=dialect.ordered_text,
        )
        for statement in (*_TABLES, *_INDEXES)
    )


def render(sql: str, dialect: _Dialect) -> str:
    """Return SQL with parameter placeholders spelled for one backend.

    Statements are authored with ``?`` and never contain a literal string, so
    substitution cannot touch anything but a parameter marker.
    """
    if "'?" in sql or "?'" in sql:
        msg = "Event-journal SQL must not embed a literal question mark"
        raise ValueError(msg)
    # Substitution is a plain string rewrite, so a marker inside an authored
    # string literal would be rewritten as if it were an identifier. No
    # statement has one and no user value reaches here -- values are bound
    # separately by both backends -- but the rewriter cannot tell, so the
    # adjacency is rejected rather than trusted, the same way a literal
    # question mark is.
    if f"'{_BYTE_ORDER_MARKER}" in sql or f"{_BYTE_ORDER_MARKER}'" in sql:
        msg = "Event-journal SQL must not embed the byte-order marker in a literal"
        raise ValueError(msg)
    sql = sql.replace(_BYTE_ORDER_MARKER, dialect.order_by_bytes)
    if dialect.placeholder == "?":
        return sql
    return sql.replace("?", dialect.placeholder)
