"""One schema definition rendered for both durable backends.

The journal, projection, and outbox exist once as SQL. A dialect supplies only
the handful of spellings SQLite and PostgreSQL genuinely disagree about, so
neither backend can drift into its own behavior.
"""

from __future__ import annotations

from dataclasses import dataclass

_BYTE_ORDER_MARKER = "/*bytes*/"

PENDING_STATE = "pending"
SETTLED_STATE = "settled"


@dataclass(frozen=True, slots=True)
class _SchemaDialect:
    """The spellings that differ between the two supported backends."""

    placeholder: str
    # A surrogate receipt-order key that is never reused after deletion,
    # because replay ordering and refresh tokens are both derived from it.
    receipt_order_column: str
    # Text that participates in ordering or range comparison. PostgreSQL's
    # default locale can order text differently from SQLite and from Python,
    # so any column a cursor compares is pinned to byte order explicitly.
    ordered_text: str
    # The same pin applied to an expression rather than a column declaration,
    # for columns that were already shipped unpinned and cannot be retyped
    # without rewriting the table.
    order_by_bytes: str


SQLITE_DIALECT = _SchemaDialect(
    placeholder="?",
    receipt_order_column="INTEGER PRIMARY KEY AUTOINCREMENT",
    ordered_text="TEXT",
    # SQLite compares TEXT with BINARY unless told otherwise, which is already
    # byte order.
    order_by_bytes="",
)

POSTGRES_DIALECT = _SchemaDialect(
    placeholder="%s",
    receipt_order_column="BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    ordered_text='TEXT COLLATE "C"',
    order_by_bytes=' COLLATE "C"',
)


_TABLES = (
    """
    CREATE TABLE IF NOT EXISTS journal_events (
        receipt_order {receipt_order_column},
        principal_id TEXT NOT NULL,
        event_id {ordered_text} NOT NULL,
        room_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        kind TEXT NOT NULL,
        sender TEXT NOT NULL,
        origin_server_ts BIGINT NOT NULL,
        source_json TEXT NOT NULL,
        semantic_consumer TEXT,
        -- The membership this event was admitted under, which is what refuses
        -- an answer written for a conversation the bot has since left. The
        -- delivery enqueue transaction derives its immutable owner here.
        membership_epoch BIGINT NOT NULL,
        state TEXT NOT NULL CHECK (state IN ('pending', 'settled')),
        UNIQUE (principal_id, event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS visible_messages (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        logical_event_id {ordered_text} NOT NULL,
        thread_id TEXT NOT NULL,
        sender TEXT NOT NULL,
        created_ts BIGINT NOT NULL,
        revision_event_id {ordered_text} NOT NULL,
        revision_ts BIGINT NOT NULL,
        content_json TEXT,
        refresh_token BIGINT,
        membership_epoch BIGINT NOT NULL,
        PRIMARY KEY (principal_id, room_id, logical_event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS unresolved_edits (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        target_event_id TEXT NOT NULL,
        sender TEXT NOT NULL,
        edit_event_id {ordered_text} NOT NULL,
        edit_ts BIGINT NOT NULL,
        content_json TEXT NOT NULL,
        PRIMARY KEY (principal_id, room_id, target_event_id, sender)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS redaction_tombstones (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        redacted_event_id TEXT NOT NULL,
        PRIMARY KEY (principal_id, room_id, redacted_event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS room_membership (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        membership_epoch BIGINT NOT NULL,
        -- A departure has been fenced and the bot has not been seen back in
        -- the room since. The bot cannot leave a room it is not in, so a
        -- second local departure while this holds is the same one arriving
        -- twice rather than a new one.
        departure_fenced INTEGER NOT NULL DEFAULT 0,
        -- Departures already fenced locally whose sync report has not arrived.
        -- A count rather than a flag: leave/rejoin/leave owes two reports, and
        -- one bit would let the second echo fence a membership it did not end.
        owed_departure_reports BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY (principal_id, room_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reported_departures (
        report_order {receipt_order_column},
        -- Matrix may replay an old leave after a later join has re-armed the
        -- room. Event identity, or the sync token when the event was omitted,
        -- keeps that replay from fencing again.
        principal_id TEXT NOT NULL,
        observation_id {ordered_text} NOT NULL,
        room_id TEXT NOT NULL,
        -- The latest journal receipt visible when this observation arrived.
        -- Synthetic sync-token observations have no event row of their own,
        -- so this is what still orders a later explicit join after them.
        journal_order BIGINT NOT NULL,
        -- Consecutive leave/ban observations are aliases for one ended
        -- membership. They share its epoch so only the run's first observation
        -- consumes a locally owed report.
        run_epoch BIGINT NOT NULL,
        -- A join closes the whole alias run. Keeping closure beside every
        -- alias lets any replayed subset recover the same answer.
        run_closed INTEGER NOT NULL DEFAULT 0,
        UNIQUE (principal_id, observation_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS interactive_questions (
        principal_id TEXT NOT NULL,
        -- One logical Matrix target can expose several revisions over time.
        -- Keeping each prompt revision immutable lets refetch restore an old
        -- visible revision without losing whether that exact prompt was used.
        question_event_id {ordered_text} NOT NULL,
        revision_event_id {ordered_text} NOT NULL,
        room_id TEXT NOT NULL,
        question_json TEXT NOT NULL,
        -- Null means this revision remains selectable whenever it is the
        -- visible projection revision. The durable source ID is its one-shot
        -- tombstone and survives source settlement.
        consumed_by_source_event_id {ordered_text},
        PRIMARY KEY (principal_id, question_event_id, revision_event_id),
        UNIQUE (principal_id, consumed_by_source_event_id),
        FOREIGN KEY (principal_id, consumed_by_source_event_id)
            REFERENCES journal_events (principal_id, event_id),
        FOREIGN KEY (principal_id, room_id, question_event_id)
            REFERENCES visible_messages (principal_id, room_id, logical_event_id)
            ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS interactive_selections (
        principal_id TEXT NOT NULL,
        source_event_id {ordered_text} NOT NULL,
        question_event_id {ordered_text} NOT NULL,
        revision_event_id {ordered_text} NOT NULL,
        selection_key TEXT NOT NULL,
        PRIMARY KEY (principal_id, source_event_id),
        FOREIGN KEY (principal_id, source_event_id)
            REFERENCES journal_events (principal_id, event_id),
        FOREIGN KEY (principal_id, question_event_id, revision_event_id)
            REFERENCES interactive_questions (principal_id, question_event_id, revision_event_id)
            ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS conversation_hydration (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        thread_id TEXT NOT NULL,
        membership_epoch BIGINT NOT NULL,
        -- Whether the walk that filled this conversation ran out of
        -- conversation rather than out of allowance. Being hydrated and being
        -- complete are different facts: a walk that stopped at the prompt
        -- window is hydrated, and a reader whose correctness is completeness
        -- has to be able to tell that from a whole conversation. It is the
        -- best answer any walk gave under this membership rather than the
        -- newest one: walks of different widths run concurrently over this
        -- row, and the narrower finishing last must not un-say the wider.
        complete INTEGER NOT NULL DEFAULT 0,
        -- The rank of the widest-ranked `HydrationPolicy` any walk here has run
        -- under this membership, whether or not it got anywhere. Completeness
        -- alone cannot distinguish a conversation nobody walked deeply from one
        -- where the deepest available walk has already been spent and failed,
        -- and a caller that cannot tell those apart repeats its whole walk on
        -- every read of a conversation that will never satisfy it. A policy
        -- rank rather than one of its ceilings, because a caller is defined by
        -- all three of them together and two policies can differ on any one.
        -- Also the best answer rather than the newest, for the reason above.
        attempted_policy_rank BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY (principal_id, room_id, thread_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS room_history_recovery (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        state TEXT NOT NULL CHECK (state IN ('repairable', 'truncated', 'repaired')),
        revision BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY (principal_id, room_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS matrix_delivery_outbox (
        principal_id TEXT NOT NULL,
        delivery_id TEXT NOT NULL,
        stage TEXT NOT NULL CHECK (stage IN ('initial', 'final')),
        event_type TEXT NOT NULL,
        room_id TEXT NOT NULL,
        membership_epoch BIGINT NOT NULL,
        thread_id TEXT NOT NULL,
        transaction_id TEXT NOT NULL,
        payload_json TEXT NOT NULL,
        -- Local semantic facts needed after acknowledgement. These are not
        -- Matrix event content and are never sent by the delivery worker.
        result_json TEXT,
        edits_event_id TEXT,
        -- A durable edit can be reserved before the INITIAL event ID exists.
        -- Its claim waits until INITIAL acknowledgement fills the target.
        edit_target_pending INTEGER NOT NULL DEFAULT 0,
        attempted INTEGER NOT NULL DEFAULT 0,
        retired INTEGER NOT NULL DEFAULT 0,
        permanent_failure_reason TEXT,
        -- The device whose transaction ID the homeserver may already hold. A
        -- transaction ID deduplicates within one device, so a row attempted by
        -- a device this process is no longer logged in as carries an ID that
        -- would be accepted as new -- and post the answer twice.
        sending_device_id TEXT,
        acknowledged_event_id TEXT,
        created_at_ns BIGINT NOT NULL,
        PRIMARY KEY (principal_id, delivery_id, stage)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS approval_cards (
        principal_id TEXT NOT NULL,
        delivery_id TEXT NOT NULL,
        continuation_id TEXT NOT NULL,
        continuation_generation BIGINT NOT NULL,
        tool_call_id TEXT NOT NULL,
        membership_epoch BIGINT NOT NULL,
        PRIMARY KEY (principal_id, delivery_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS background_approval_calls (
        principal_id TEXT NOT NULL,
        delivery_id TEXT NOT NULL,
        run_id TEXT NOT NULL,
        call_id TEXT NOT NULL,
        expires_at_ns BIGINT NOT NULL,
        decision TEXT CHECK (decision IS NULL OR decision IN ('approved', 'denied', 'expired')),
        reason TEXT,
        PRIMARY KEY (principal_id, delivery_id),
        UNIQUE (principal_id, run_id, call_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS approval_action_tombstones (
        principal_id TEXT NOT NULL,
        room_id TEXT NOT NULL,
        card_event_id TEXT NOT NULL,
        PRIMARY KEY (principal_id, card_event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS approval_continuations (
        principal_id TEXT NOT NULL,
        approval_id TEXT NOT NULL UNIQUE,
        entity_name TEXT NOT NULL,
        state TEXT NOT NULL CHECK (state IN ('waiting', 'ready', 'claimed', 'failing')),
        generation BIGINT NOT NULL DEFAULT 0,
        runtime_generation TEXT,
        failure_reason TEXT,
        context_json TEXT NOT NULL,
        created_at_ns BIGINT NOT NULL,
        PRIMARY KEY (principal_id, approval_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS approval_continuation_sources (
        principal_id TEXT NOT NULL,
        approval_id TEXT NOT NULL,
        event_id TEXT NOT NULL,
        source_ordinal BIGINT NOT NULL,
        PRIMARY KEY (principal_id, approval_id, event_id),
        UNIQUE (principal_id, event_id),
        UNIQUE (principal_id, approval_id, source_ordinal),
        FOREIGN KEY (principal_id, approval_id)
            REFERENCES approval_continuations (principal_id, approval_id) ON DELETE CASCADE,
        FOREIGN KEY (principal_id, event_id)
            REFERENCES journal_events (principal_id, event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS approval_continuation_calls (
        principal_id TEXT NOT NULL,
        approval_id TEXT NOT NULL,
        generation BIGINT NOT NULL,
        tool_call_id TEXT NOT NULL,
        call_ordinal BIGINT NOT NULL,
        tool_name TEXT NOT NULL,
        invoking_agent TEXT NOT NULL,
        expires_at_ns BIGINT NOT NULL,
        decision TEXT CHECK (decision IS NULL OR decision IN ('approved', 'denied', 'expired')),
        reason TEXT,
        human_approval_required BOOLEAN,
        PRIMARY KEY (principal_id, approval_id, generation, tool_call_id),
        UNIQUE (principal_id, approval_id, generation, call_ordinal),
        FOREIGN KEY (principal_id, approval_id)
            REFERENCES approval_continuations (principal_id, approval_id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS turn_records (
        -- Scoped to the agent, not to a journal principal. Every other table
        -- here is per (agent, Matrix identity), because what it holds is only
        -- meaningful next to the sync that produced it. A turn record is not:
        -- it is the proof that a message was already answered, and a bot that
        -- re-logs in under a new Matrix ID must not answer everything twice.
        -- Sharing the database is what makes this transactional with a
        -- settlement; sharing the scope key is not required and would be wrong.
        agent_name TEXT NOT NULL,
        -- A coalesced turn answers several sources at once and is reachable by
        -- any of them, so one record is stored once per event that indexes it.
        index_event_id TEXT NOT NULL,
        anchor_event_id TEXT NOT NULL,
        record_json TEXT NOT NULL,
        PRIMARY KEY (agent_name, index_event_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS journal_identity (
        -- One row, ever. A Matrix sync token is only meaningful next to the
        -- store that consumed the events it already covers: resuming from a
        -- token saved before this database was created would skip every event
        -- between, and nothing downstream would notice the gap. The generation
        -- is written once when the store is first opened and never rewritten,
        -- so a checkpoint that names a different one is from a database that
        -- no longer exists.
        singleton BOOLEAN NOT NULL PRIMARY KEY,
        generation TEXT NOT NULL
    )
    """,
)


_INDEXES = (
    """
    CREATE INDEX IF NOT EXISTS reported_departures_open
    ON reported_departures (principal_id, room_id, report_order)
    WHERE run_closed = 0
    """,
    """
    CREATE INDEX IF NOT EXISTS interactive_selections_revision
    ON interactive_selections (principal_id, question_event_id, revision_event_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS journal_events_pending
    ON journal_events (principal_id, receipt_order)
    WHERE state = 'pending'
    """,
    """
    -- The replay guard asks whether one conversation holds newer unfinished
    -- work. `journal_events_pending` orders the principal's whole pending set
    -- by receipt, so answering from it means filtering every pending row in
    -- every room; this one goes straight to the thread and the timestamp.
    CREATE INDEX IF NOT EXISTS journal_events_pending_thread
    ON journal_events (principal_id, room_id, thread_id, origin_server_ts)
    WHERE state = 'pending'
    """,
    """
    CREATE INDEX IF NOT EXISTS visible_messages_page
    ON visible_messages (principal_id, room_id, thread_id, created_ts, logical_event_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS visible_messages_revision
    ON visible_messages (principal_id, room_id, revision_event_id)
    """,
    """
    CREATE INDEX IF NOT EXISTS visible_messages_refresh
    ON visible_messages (principal_id, room_id, thread_id)
    WHERE refresh_token IS NOT NULL
    """,
    """
    -- Covers the recovery scan's whole ORDER BY, not just its prefix. Stopping
    -- at `created_at_ns` left SQLite building a temporary b-tree for the last
    -- two terms on every pass, and PostgreSQL cannot satisfy an ORDER BY from
    -- an index that matches only its prefix either. The trailing columns carry
    -- the same byte-order pin as the cursor comparison, because an index in the
    -- server's own collation would not be usable for this ordering at all.
    CREATE INDEX IF NOT EXISTS matrix_delivery_outbox_unacknowledged_scan
    ON matrix_delivery_outbox (
        principal_id, event_type, created_at_ns, delivery_id/*bytes*/, stage/*bytes*/
    )
    WHERE acknowledged_event_id IS NULL AND retired = 0
    """,
    """
    CREATE INDEX IF NOT EXISTS matrix_delivery_outbox_room_scan
    ON matrix_delivery_outbox (
        principal_id, room_id, stage, created_at_ns, delivery_id/*bytes*/
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS approval_cards_continuation
    ON approval_cards (continuation_id/*bytes*/, continuation_generation, tool_call_id/*bytes*/)
    """,
    """
    CREATE INDEX IF NOT EXISTS approval_continuations_owner_scan
    ON approval_continuations (entity_name/*bytes*/, approval_id/*bytes*/)
    """,
)


def _expand_byte_order(sql: str, dialect: _SchemaDialect) -> str:
    """Spell the byte-order pin for one backend."""
    return sql.replace(_BYTE_ORDER_MARKER, dialect.order_by_bytes)


def schema_statements(dialect: _SchemaDialect) -> tuple[str, ...]:
    """Return every DDL statement needed to create the current schema.

    The byte-order marker is substituted here as well as in queries. An index
    whose trailing columns sort in the server's own collation cannot satisfy an
    ORDER BY that pins them to byte order -- PostgreSQL simply declines to use
    it and sorts instead. Leaving the marker unexpanded is silent on SQLite,
    whose default text collation is already byte order, so the mismatch shows up
    only on the backend that is not measured by a local query-plan test.
    """
    return tuple(
        _expand_byte_order(statement, dialect).format(
            receipt_order_column=dialect.receipt_order_column,
            ordered_text=dialect.ordered_text,
        )
        for statement in (*_TABLES, *_INDEXES)
    )


def render(sql: str, dialect: _SchemaDialect) -> str:
    """Return SQL with parameter placeholders spelled for one backend.

    Statements are authored with ``?`` and never contain a literal string, so
    substitution cannot touch anything but a parameter marker.
    """
    if "'?" in sql or "?'" in sql:
        msg = "Event-journal SQL must not embed a literal question mark"
        raise ValueError(msg)
    # Substitution is a plain string rewrite, so a marker inside an authored
    # string literal would be rewritten as if it were an identifier. No
    # statement has one and no user value reaches here -- values are bound
    # separately by both backends -- but the rewriter cannot tell, so the
    # adjacency is rejected rather than trusted, the same way a literal
    # question mark is.
    if f"'{_BYTE_ORDER_MARKER}" in sql or f"{_BYTE_ORDER_MARKER}'" in sql:
        msg = "Event-journal SQL must not embed the byte-order marker in a literal"
        raise ValueError(msg)
    sql = sql.replace(_BYTE_ORDER_MARKER, dialect.order_by_bytes)
    if dialect.placeholder == "?":
        return sql
    return sql.replace("?", dialect.placeholder)
